[project]
name = "bs-ml-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.10.0.84",
    "pytesseract>=0.3.13",
    "requests>=2.32.3",
]
